### ISSUE TITLE
Software Heritage Action

### ISSUE THREAD

**Issue by cgreene** [greenelab/backup#1]
I'd love an action that could be placed into a repo of scientific software to trigger the software heritage save API: https://archive.softwareheritage.org/api/1/origin/save/doc/

Ideally this could happen on commits to either any branch or a specific branch.

**Comment by vincerubinetti** [comment]
The script was completed, but I never made this into a more reusable action. Look into this again. It could be a collaboration with the Software Heritage to make an official action on the Actions Marketplace.

**Comment by vincerubinetti** [comment]
So I started to make this, but I've now realized it may be not necessary at all.

I found [this in the Software Heritage docs](https://docs.softwareheritage.org/user/save_code_now/webhooks/index.html#github). Apparently you can send this particular API endpoint a webhook from GitHub, and it will automatically start a backup.

Then, I also realized you can make [organization level](https://docs.github.com/en/rest/orgs/webhooks?apiVersion=2022-11-28) webhooks in GitHub which send out any time there is a commit to any repo in the org...

So I tested it out, and it seems to work! First I set up just a single org-level webhook, pointing to the right SH endpoint:

<img width="866" alt="Screenshot 2023-07-18 at 12 13 19 PM" src="https://github.com/greenelab/backup/assets/8326331/a0d6e211-a99a-40a4-a12a-de91510d3582">

Then I made a test commit, updating the readme of this repo, and seconds later, on the SH website:

<img width="1154" alt="Screenshot 2023-07-18 at 12 09 46 PM" src="https://github.com/greenelab/backup/assets/8326331/f3117afe-6374-4979-a8ac-a5013e70313f">

This should theoretically be better than our script solution here. It only runs when there is a commit, and only on the repo that had activity. And it shouldn't ever stop running, like the cron job we have here does. And, you don't have to have a dedicated repo in your org for this, it's just an org config setting.

I think I'll add instructions on how to do this to the top of this repo as the preferred method (assuming further testing proves that this works). I'll still fix the bug in #5, and update the code to link to the appropriate SH docs I found.

It may not work for Wikis, I'll try to test that out. The original reason I had these scripts scan for wikis (a whole additional process, since they aren't returned in the normal listing of an org's repos) is because the Lab Website Template docs were originally stored in a wiki, but they are now on GitBook. I think very few people use wikis though.

**Comment by vincerubinetti** [comment]
Related, they have a github action already, but it only works for single repositories:
https://github.com/sdruskat/swh-save-action

We could make an issue there for supporting all of an org's repos.
